# Generated by Django 5.0.6 on 2024-06-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ingredientes', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Pasantes',
        ),
    ]
