# Generated by Django 5.0.6 on 2024-07-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_tareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
    ]
